// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-tickets.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function resolveWorkspaceId(supabase) {
  const { data, error } = await supabase.from("workspaces").select("id").eq("slug", "default").maybeSingle();
  if (error) throw new Error(error.message);
  if (!data?.id) throw new Error("No accessible workspace found for this user");
  return data.id;
}

// src/lib/mcp/tools/list-tickets.ts
var list_tickets_default = defineTool({
  name: "list_tickets",
  title: "List tickets",
  description: "List tickets (stories) in the workspace, optionally filtered by status, type, priority, epic, or sprint.",
  inputSchema: {
    status: z.enum(["backlog", "todo", "in_progress", "in_review", "done"]).optional().describe("Filter by workflow status."),
    type: z.enum(["bug", "feature", "task"]).optional().describe("Filter by ticket type."),
    priority: z.enum(["P0", "P1", "P2"]).optional().describe("Filter by priority."),
    epic_id: z.string().uuid().optional().describe("Filter by epic id."),
    sprint_id: z.string().uuid().optional().describe("Filter by sprint id."),
    limit: z.number().int().min(1).max(100).default(25).describe("Maximum rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, type, priority, epic_id, sprint_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    try {
      const workspaceId = await resolveWorkspaceId(supabase);
      let query = supabase.from("tickets").select("id,ticket_key,title,status,type,priority,story_points,epic_id,sprint_id,assignee_id,created_at").eq("workspace_id", workspaceId).order("created_at", { ascending: false }).limit(limit ?? 25);
      if (status) query = query.eq("status", status);
      if (type) query = query.eq("type", type);
      if (priority) query = query.eq("priority", priority);
      if (epic_id) query = query.eq("epic_id", epic_id);
      if (sprint_id) query = query.eq("sprint_id", sprint_id);
      const { data, error } = await query;
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data ?? []) }],
        structuredContent: { tickets: data ?? [] }
      };
    } catch (err) {
      return { content: [{ type: "text", text: err.message }], isError: true };
    }
  }
});

// src/lib/mcp/tools/get-ticket.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_ticket_default = defineTool2({
  name: "get_ticket",
  title: "Get ticket",
  description: "Fetch one ticket with its description, acceptance criteria, labels and comments.",
  inputSchema: {
    ticket: z2.string().min(1).describe("Ticket id (uuid) or ticket key such as AUTH-101.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ ticket }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    try {
      const workspaceId = await resolveWorkspaceId(supabase);
      const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(ticket);
      const { data: row, error } = await supabase.from("tickets").select("*").eq("workspace_id", workspaceId).eq(isUuid ? "id" : "ticket_key", ticket).maybeSingle();
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      if (!row) return { content: [{ type: "text", text: `Ticket not found: ${ticket}` }], isError: true };
      const [labels, comments] = await Promise.all([
        supabase.from("ticket_labels").select("label").eq("ticket_id", row.id),
        supabase.from("comments").select("id,content,created_at,author_id").eq("ticket_id", row.id).order("created_at", { ascending: true })
      ]);
      const result = {
        ...row,
        labels: (labels.data ?? []).map((l) => l.label),
        comments: comments.data ?? []
      };
      return {
        content: [{ type: "text", text: JSON.stringify(result) }],
        structuredContent: { ticket: result }
      };
    } catch (err) {
      return { content: [{ type: "text", text: err.message }], isError: true };
    }
  }
});

// src/lib/mcp/tools/create-ticket.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var create_ticket_default = defineTool3({
  name: "create_ticket",
  title: "Create ticket",
  description: "Create a new ticket (story) in the backlog with title, description and acceptance criteria.",
  inputSchema: {
    title: z3.string().trim().min(3).max(200).describe("Short ticket title."),
    description: z3.string().trim().min(1).describe("What needs to be done."),
    acceptance_criteria: z3.string().trim().min(1).describe("What 'done' looks like."),
    type: z3.enum(["bug", "feature", "task"]).default("task"),
    priority: z3.enum(["P0", "P1", "P2"]).default("P2"),
    story_points: z3.number().int().min(1).max(21).default(3),
    epic_id: z3.string().uuid().optional().describe("Optional epic to attach the ticket to."),
    sprint_id: z3.string().uuid().optional().describe("Optional sprint to attach the ticket to.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    try {
      const workspaceId = await resolveWorkspaceId(supabase);
      const { count } = await supabase.from("tickets").select("id", { count: "exact", head: true }).eq("workspace_id", workspaceId);
      const ticketKey = `TICK-${100 + (count ?? 0) + 1}`;
      const { data, error } = await supabase.from("tickets").insert({
        workspace_id: workspaceId,
        ticket_key: ticketKey,
        title: input.title,
        description: input.description,
        acceptance_criteria: input.acceptance_criteria,
        status: "backlog",
        type: input.type ?? "task",
        priority: input.priority ?? "P2",
        story_points: input.story_points ?? 3,
        epic_id: input.epic_id ?? null,
        sprint_id: input.sprint_id ?? null
      }).select().maybeSingle();
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data) }],
        structuredContent: { ticket: data }
      };
    } catch (err) {
      return { content: [{ type: "text", text: err.message }], isError: true };
    }
  }
});

// src/lib/mcp/tools/update-ticket-status.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var update_ticket_status_default = defineTool4({
  name: "update_ticket_status",
  title: "Update ticket status",
  description: "Move a ticket to another workflow status (backlog, todo, in_progress, in_review, done).",
  inputSchema: {
    ticket: z4.string().min(1).describe("Ticket id (uuid) or ticket key such as AUTH-101."),
    status: z4.enum(["backlog", "todo", "in_progress", "in_review", "done"])
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ ticket, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    try {
      const workspaceId = await resolveWorkspaceId(supabase);
      const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(ticket);
      const { data, error } = await supabase.from("tickets").update({
        status,
        completed_at: status === "done" ? (/* @__PURE__ */ new Date()).toISOString() : null
      }).eq("workspace_id", workspaceId).eq(isUuid ? "id" : "ticket_key", ticket).select("id,ticket_key,title,status,completed_at").maybeSingle();
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      if (!data) return { content: [{ type: "text", text: `Ticket not found: ${ticket}` }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data) }],
        structuredContent: { ticket: data }
      };
    } catch (err) {
      return { content: [{ type: "text", text: err.message }], isError: true };
    }
  }
});

// src/lib/mcp/tools/list-epics.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var list_epics_default = defineTool5({
  name: "list_epics",
  title: "List epics",
  description: "List the workspace epics with their target quarter and dates.",
  inputSchema: {
    limit: z5.number().int().min(1).max(100).default(50).describe("Maximum rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    try {
      const workspaceId = await resolveWorkspaceId(supabase);
      const { data, error } = await supabase.from("epics").select("id,name,color,target_quarter,start_date,end_date,sort_order").eq("workspace_id", workspaceId).order("sort_order", { ascending: true }).limit(limit ?? 50);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data ?? []) }],
        structuredContent: { epics: data ?? [] }
      };
    } catch (err) {
      return { content: [{ type: "text", text: err.message }], isError: true };
    }
  }
});

// src/lib/mcp/tools/list-sprints.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z6 } from "npm:zod@^3.25.76";
var list_sprints_default = defineTool6({
  name: "list_sprints",
  title: "List sprints",
  description: "List sprints with dates, goal and whether they are active.",
  inputSchema: {
    active_only: z6.boolean().default(false).describe("Return only the active sprint(s).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ active_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    try {
      const workspaceId = await resolveWorkspaceId(supabase);
      let query = supabase.from("sprints").select("id,name,goal,start_date,end_date,is_active").eq("workspace_id", workspaceId).order("start_date", { ascending: false });
      if (active_only) query = query.eq("is_active", true);
      const { data, error } = await query;
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data ?? []) }],
        structuredContent: { sprints: data ?? [] }
      };
    } catch (err) {
      return { content: [{ type: "text", text: err.message }], isError: true };
    }
  }
});

// src/lib/mcp/tools/sprint-summary.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z7 } from "npm:zod@^3.25.76";
var sprint_summary_default = defineTool7({
  name: "sprint_summary",
  title: "Sprint summary",
  description: "Summarise a sprint: ticket counts and story points by status, plus completion percentage.",
  inputSchema: {
    sprint_id: z7.string().uuid().optional().describe("Sprint id. Defaults to the active sprint.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ sprint_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    try {
      const workspaceId = await resolveWorkspaceId(supabase);
      let sprintId = sprint_id;
      let sprintName = null;
      if (!sprintId) {
        const { data: data2 } = await supabase.from("sprints").select("id,name").eq("workspace_id", workspaceId).eq("is_active", true).order("start_date", { ascending: false }).limit(1).maybeSingle();
        if (!data2) return { content: [{ type: "text", text: "No active sprint found" }], isError: true };
        sprintId = data2.id;
        sprintName = data2.name;
      }
      const { data, error } = await supabase.from("tickets").select("status,story_points").eq("workspace_id", workspaceId).eq("sprint_id", sprintId);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      const rows = data ?? [];
      const byStatus = {};
      let totalPoints = 0;
      let donePoints = 0;
      for (const r of rows) {
        const pts = r.story_points ?? 0;
        byStatus[r.status] ??= { tickets: 0, points: 0 };
        byStatus[r.status].tickets += 1;
        byStatus[r.status].points += pts;
        totalPoints += pts;
        if (r.status === "done") donePoints += pts;
      }
      const summary = {
        sprint_id: sprintId,
        sprint_name: sprintName,
        total_tickets: rows.length,
        total_points: totalPoints,
        done_points: donePoints,
        completion_percent: totalPoints ? Math.round(donePoints / totalPoints * 100) : 0,
        by_status: byStatus
      };
      return {
        content: [{ type: "text", text: JSON.stringify(summary) }],
        structuredContent: { summary }
      };
    } catch (err) {
      return { content: [{ type: "text", text: err.message }], isError: true };
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "cnaikxlyuxhtwkkahlpt";
var mcp_default = defineMcp({
  name: "sprint-companion-lovable-template",
  title: "Sprint Companion - Lovable Template",
  version: "0.1.0",
  instructions: "Tools for the sprint board: browse epics, sprints and tickets, read a ticket in full, create tickets in the backlog, move tickets between statuses, and summarise sprint progress. All calls act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_epics_default,
    list_sprints_default,
    list_tickets_default,
    get_ticket_default,
    create_ticket_default,
    update_ticket_status_default,
    sprint_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
