import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertCircle, CheckCircle2, Compass, ExternalLink, FolderGit2, GitBranch, Globe2, Loader2, LockKeyhole, RefreshCw, ShieldCheck, Trash2 } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { ProfileAvatar } from '@/components/apivue/ProfileBits';
import { toast } from '@/hooks/use-toast';
import { useRemoveProfile, useSyncProfile, useTrackedProfiles } from '@/hooks/use-profiles';
import { connectCodeforces, connectGitHub, connectPublicProfile, connectStackOverflow, disconnectCodeforces, disconnectGitHub, disconnectLeetCode, disconnectCodewars, disconnectStackOverflow, getIntegrationStatus, syncGitHub, syncIntegration } from '@/lib/integrations/api';
import { getIntegration } from '@/lib/integrations/registry';
import type { ConnectedAccount, IntegrationId, IntegrationStatus, TrackedProfile } from '@/lib/integrations/types';

const verifiedIds: IntegrationId[] = ['github', 'codeforces', 'stackoverflow'];
const publicIds: IntegrationId[] = ['leetcode', 'codewars'];
function pick<T>(...values: Array<T | undefined | null>): T | undefined { return values.find((v) => v !== undefined && v !== null && v !== '') as T | undefined; }

function Account({ account, name, busy, onSync, onRemove, githubProfile }: { account: ConnectedAccount; name: string; busy: boolean; onSync: () => void; onRemove: () => void; githubProfile?: TrackedProfile }) {
  const handle = pick(account.username, account.handle);
  const privateAccess = githubProfile?.data?.privateAccess === true;
  const repoCount = githubProfile?.data?.accessibleRepoCount;
  const verified = account.ownershipVerified || verifiedIds.includes(name.toLowerCase() as IntegrationId);
  return <div className="rounded-xl border bg-background/60 p-4">
    <div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-emerald-500/10"><CheckCircle2 className="h-5 w-5 text-emerald-600" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-semibold">{verified ? 'Verified connection' : 'Public profile tracked'}</p><Badge variant="outline" className={verified ? 'border-emerald-500/30' : 'border-sky-500/30'}>{verified ? 'Verified' : 'Public data only'}</Badge>{name === 'GitHub' && privateAccess && <Badge className="border-0 bg-emerald-500/15 text-emerald-700">Private access</Badge>}</div><p className="mt-1 truncate text-sm font-semibold">{handle ? `@${handle}` : 'Account connected'}</p><p className="mt-1 text-[11px] text-muted-foreground">{account.lastSyncedAt ? `Last synced ${new Date(account.lastSyncedAt).toLocaleString()}` : 'Profile data available'}</p></div></div>
    {name === 'GitHub' && <div className="mt-4 grid gap-2 sm:grid-cols-2"><div className="rounded-lg border p-3"><div className="flex items-center gap-2 text-[11px] text-muted-foreground"><ShieldCheck className="h-3.5 w-3.5" /> Access level</div><p className="mt-1 text-sm font-semibold">{privateAccess ? 'Private + public repositories' : 'Public repositories'}</p></div><div className="rounded-lg border p-3"><div className="flex items-center gap-2 text-[11px] text-muted-foreground"><FolderGit2 className="h-3.5 w-3.5" /> Repository access</div><p className="mt-1 text-sm font-semibold">{typeof repoCount === 'number' ? `${repoCount} accessible` : 'Ready to sync'}</p></div></div>}
    {!verified && <p className="mt-3 rounded-lg border border-sky-500/20 bg-sky-500/[0.05] p-3 text-xs text-muted-foreground">Anyone can track this public profile. APIVue is not claiming that this account belongs to you.</p>}
    <div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={onSync} disabled={busy}><RefreshCw className="mr-1.5 h-3.5 w-3.5" /> Sync now</Button><Button size="sm" variant="outline" onClick={onRemove} disabled={busy} className="text-destructive"><Trash2 className="mr-1.5 h-3.5 w-3.5" /> Remove</Button>{name === 'GitHub' && githubProfile?.id && <Link to="/dashboard/integrations/github" className="inline-flex items-center rounded-md border px-3 text-xs font-medium"><GitBranch className="mr-1.5 h-3.5 w-3.5" /> GitHub data</Link>}</div>
  </div>;
}

function PublicForm({ id, name, placeholder, busy, onConnect }: { id: IntegrationId; name: string; placeholder: string; busy: boolean; onConnect: (id: IntegrationId, handle: string) => void }) {
  const [handle, setHandle] = useState('');
  return <form onSubmit={(e) => { e.preventDefault(); if (handle.trim()) onConnect(id, handle.trim()); }} className="flex flex-col gap-2 sm:flex-row"><Input value={handle} onChange={(e) => setHandle(e.target.value)} placeholder={placeholder} disabled={busy} autoComplete="off" spellCheck={false} /><Button type="submit" disabled={busy || !handle.trim()}>{busy ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Globe2 className="mr-1.5 h-3.5 w-3.5" />}{busy ? 'Loading…' : `Track ${name}`}</Button></form>;
}

function PublicList({ profiles, busyId, onRefresh, onRemove, name }: { profiles: TrackedProfile[]; busyId: string | null; onRefresh: (id: string, platform: string, handle: string) => void; onRemove: (id: string, handle: string) => void; name: string }) {
  return <div className="mt-4 space-y-2 border-t pt-4"><p className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground">Public profiles tracked on {name}</p>{profiles.length ? profiles.map((profile) => { const url = pick(profile.profileUrl, profile.profile_url); const display = pick(profile.displayName, profile.display_name, profile.handle); const busy = busyId === profile.id; return <div key={profile.id} className="flex items-center gap-3 rounded-lg border p-3"><ProfileAvatar profile={profile} size="sm" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{display}</p><p className="truncate text-[11px] text-muted-foreground">@{profile.handle}</p></div>{url && <a href={url} target="_blank" rel="noreferrer noopener" className="rounded p-1.5 hover:bg-muted"><ExternalLink className="h-3.5 w-3.5" /></a>}<button type="button" onClick={() => onRefresh(profile.id, profile.platform, profile.handle)} disabled={busy} className="rounded p-1.5 hover:bg-muted">{busy ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <RefreshCw className="h-3.5 w-3.5" />}</button><button type="button" onClick={() => onRemove(profile.id, profile.handle)} className="rounded p-1.5 hover:bg-destructive/10"><Trash2 className="h-3.5 w-3.5" /></button></div>; }) : <p className="rounded-lg border border-dashed p-3 text-xs text-muted-foreground">No public profiles tracked yet.</p>}</div>;
}

export function IntegrationModesView() {
  const { data: profiles = [], isLoading, error } = useTrackedProfiles();
  const remove = useRemoveProfile(); const syncProfile = useSyncProfile();
  const [status, setStatus] = useState<IntegrationStatus | null>(null); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState<IntegrationId | null>(null); const [busyProfile, setBusyProfile] = useState<string | null>(null); const [params] = useSearchParams();
  const reload = useCallback(async () => { try { setStatus(await getIntegrationStatus()); setMessage(null); } catch (e) { setMessage((e as Error).message); } }, []);
  useEffect(() => { void reload(); }, [reload]);
  useEffect(() => { if (params.get('github') === 'connected') { void reload(); toast({ title: 'GitHub connected', description: 'Your authorized GitHub data is ready.' }); } else if (params.get('github') === 'error') setMessage(params.get('message') ?? 'GitHub connection failed.'); }, [params, reload]);
  const connectVerified = useCallback(async (id: IntegrationId) => { setBusy(id); setMessage(null); try { if (id === 'github') await connectGitHub(); else if (id === 'codeforces') await connectCodeforces(); else await connectStackOverflow(); } catch (e) { setMessage((e as Error).message); toast({ title: `Could not connect ${getIntegration(id).name}`, description: (e as Error).message, variant: 'destructive' }); } finally { setBusy(null); } }, []);
  const connectPublic = useCallback(async (id: IntegrationId, handle: string) => { setBusy(id); setMessage(null); try { await connectPublicProfile(id as 'leetcode' | 'codewars', handle); await reload(); toast({ title: `${getIntegration(id).name} profile tracked`, description: `Public data for @${handle.replace(/^@/, '')} is now available.` }); } catch (e) { setMessage((e as Error).message); toast({ title: `Could not load ${getIntegration(id).name}`, description: (e as Error).message, variant: 'destructive' }); } finally { setBusy(null); } }, [reload]);
  const sync = useCallback(async (id: IntegrationId) => { setBusy(id); try { if (id === 'github') await syncGitHub(); else await syncIntegration(id); await reload(); } catch (e) { setMessage((e as Error).message); } finally { setBusy(null); } }, [reload]);
  const removeAccount = useCallback(async (id: IntegrationId) => { if (!window.confirm(`Remove ${getIntegration(id).name}?`)) return; setBusy(id); try { if (id === 'github') await disconnectGitHub(); else if (id === 'codeforces') await disconnectCodeforces(); else if (id === 'leetcode') await disconnectLeetCode(); else if (id === 'codewars') await disconnectCodewars(); else await disconnectStackOverflow(); await reload(); } catch (e) { setMessage((e as Error).message); } finally { setBusy(null); } }, [reload]);
  const refresh = useCallback(async (id: string, platform: string, handle: string) => { setBusyProfile(id); try { await syncProfile.mutateAsync({ platform, handle }); await reload(); } catch (e) { toast({ title: 'Refresh failed', description: (e as Error).message, variant: 'destructive' }); } finally { setBusyProfile(null); } }, [reload, syncProfile]);
  const removeProfile = useCallback((id: string, handle: string) => { if (!window.confirm(`Remove ${handle}?`)) return; remove.mutate(id, { onSuccess: () => void reload(), onError: (e) => toast({ title: 'Remove failed', description: (e as Error).message, variant: 'destructive' }) }); }, [reload, remove]);
  const byPlatform = useMemo(() => profiles.reduce<Record<string, TrackedProfile[]>>((all, profile) => { (all[profile.platform] ??= []).push(profile); return all; }, {}), [profiles]);
  const verifiedCount = verifiedIds.filter((id) => status?.[id]?.connected).length;
  const publicCount = publicIds.reduce((n, id) => n + (byPlatform[id]?.length ?? 0), 0);
  const verifiedCard = (id: IntegrationId) => { const def = getIntegration(id); const account = status?.[id]; if (account?.connected) return <Account account={account} name={def.name} busy={busy === id} onSync={() => void sync(id)} onRemove={() => void removeAccount(id)} githubProfile={profiles.find((p) => p.platform === 'github')} />; return <div className="rounded-xl border p-4"><div className="flex items-start gap-3"><LockKeyhole className="mt-1 h-5 w-5 text-primary" /><div><h3 className="font-semibold">{def.name}</h3><p className="mt-1 text-xs text-muted-foreground">{def.description}</p><p className="mt-2 text-[11px] text-muted-foreground">{def.handleHint}</p></div></div><Button className="mt-4" onClick={() => void connectVerified(id)} disabled={busy === id}>{busy === id && <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" />}{busy === id ? 'Connecting…' : `Connect with ${def.name}`}</Button></div>; };
  const publicCard = (id: IntegrationId) => { const def = getIntegration(id); const account = status?.[id]; if (account?.connected) return <Account account={account} name={def.name} busy={busy === id} onSync={() => void sync(id)} onRemove={() => void removeAccount(id)} />; return <div className="rounded-xl border p-4"><div className="flex items-start gap-3"><Globe2 className="mt-1 h-5 w-5 text-sky-600" /><div><div className="flex items-center gap-2"><h3 className="font-semibold">{def.name}</h3><Badge variant="outline" className="border-sky-500/30">Public data</Badge></div><p className="mt-1 text-xs text-muted-foreground">{def.description}</p><p className="mt-2 text-[11px] text-muted-foreground">{def.handleHint}</p></div></div><div className="mt-4"><PublicForm id={id} name={def.name} placeholder={def.handlePlaceholder} busy={busy === id} onConnect={connectPublic} /></div><PublicList profiles={byPlatform[id] ?? []} busyId={busyProfile} onRefresh={refresh} onRemove={removeProfile} name={def.name} /></div>; };

  return <div className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6">
    <div className="rounded-2xl border bg-gradient-to-br from-primary/[0.10] via-background to-background p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><Badge variant="outline" className="border-primary/30">Data engine</Badge><span className="text-[11px] text-muted-foreground">Two connection modes</span></div><h1 className="mt-3 text-2xl font-bold tracking-tight sm:text-3xl">Integrations</h1><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Use verified connections when a provider supports authorization. Otherwise, track public developer data without claiming ownership.</p></div><div className="flex gap-2"><div className="rounded-xl border bg-background/70 px-3 py-2"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">Verified</p><p className="text-lg font-bold">{verifiedCount}/{verifiedIds.length}</p></div><div className="rounded-xl border bg-background/70 px-3 py-2"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">Public profiles</p><p className="text-lg font-bold">{publicCount}</p></div><Link to="/dashboard/explore"><Button size="sm" variant="outline"><Compass className="mr-1.5 h-3.5 w-3.5" /> Explore</Button></Link></div></div></div>
    {message && <div className="flex items-start gap-3 rounded-xl border border-amber-500/30 bg-amber-500/[0.08] p-4 text-sm"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" /><div><p className="font-medium">Integration service message</p><p className="mt-0.5 text-xs text-muted-foreground">{message}</p></div></div>}
    {error && <div className="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">Could not load tracked profiles: {(error as Error).message}</div>}
    <Card className="border-emerald-500/20"><CardContent className="p-5"><div className="flex items-start gap-3"><ShieldCheck className="mt-1 h-5 w-5 text-emerald-600" /><div><h2 className="font-semibold">Verified connections</h2><p className="mt-1 text-xs text-muted-foreground">These providers can establish an account connection. APIVue can label the resulting account as verified.</p></div></div><div className="mt-5 grid gap-4 lg:grid-cols-3">{verifiedIds.map(verifiedCard)}</div></CardContent></Card>
    <Card className="border-sky-500/20"><CardContent className="p-5"><div className="flex items-start gap-3"><Globe2 className="mt-1 h-5 w-5 text-sky-600" /><div><h2 className="font-semibold">Public data — no verification required</h2><p className="mt-1 text-xs text-muted-foreground">Track any public profile. No GitHub account, Clan change, profile edit, webhook, or verification code is required.</p></div></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{publicIds.map(publicCard)}</div></CardContent></Card>
    {isLoading && <div className="flex items-center justify-center gap-2 py-3 text-xs text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin" /> Loading integration data…</div>}
  </div>;
}
